#!/usr/bin/env bash
kbd_mode -s
sh -c 'dumpkeys -k|grep -v Incr_Console|grep -v Decr_Console|grep -v Last_Console|loadkeys'

echo "#!/bin/sh
case "${1}" in
resume|thaw)
nmcli radio wifi off && nmcli radio wifi on;;
esac
" > /etc/pm/sleep.d/10_resume_wifi

chmod +x /etc/pm/sleep.d/10_resume_wifi
nmcli radio wifi

cp ./fixbt /lib/systemd/system-sleep/fixbt
