#!/usr/bin/env bash

echo "#!/bin/sh
case "${1}" in
resume|thaw)
nmcli radio wifi off && nmcli radio wifi on;;
esac
" > /etc/pm/sleep.d/10_resume_wifi

chmod +x /etc/pm/sleep.d/10_resume_wifi
nmcli radio wifi

cp ./fixbt /lib/systemd/system-sleep/fixbt
