#!/usr/bin/env bash
set -e

echo "Tmux"
(cd tmux && ./install)

echo "Base Tools"
(cd programming && ./install)

echo "Installing Haskell"
(cd haskell && ./install)

echo "Install Ocaml"
(cd ocaml && ./install)

echo "Vim"
(cd vim && ./install)

echo "Zsh"
(cd zsh && ./install)

echo "Google cloud tools"
(cd google && ./install)

echo "[+] Reboot for shell changes"
