#!/usr/bin/env bash

curl -o gcloud.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-238.0.0-linux-x86_64.tar.gz
tar zxvf gcloud.tar.gz google-cloud-sdk
rm gcloud.tar.gz
./google-cloud-sdk/install.sh
