#!/usr/bin/env bash

sudo apt install vim-gtk

git clone https://github.com/jawline/vim.git temp_vim

cp -fr ./temp_vim/.vimrc ~/
cp -fr ./temp_vim/.vim/ ~/
cp -fr ./temp_vim/.tmux.conf ~/
rm -rf temp_vim/

cat .bashrc >> ~/.bashrc
