#!/usr/bin/env bash
set -euvx
cp configuration.nix /etc/nixos/configuration.nix
cp home.nix /etc/nixos/home.nix
rm -rf /etc/nixos/etc/
cp -r ./etc /etc/nixos/etc
nixos-rebuild --show-trace --verbose switch
