#!/usr/bin/env bash
sudo apt-get install i3 i3-wm dunst i3lock i3status suckless-tools compton hsetroot rxvt-unicode xsel rofi fonts-noto fonts-mplus xsettingsd lxappearance scrot viewnior
sudo mkdir -p /etc/X11/xorg.conf.d
sudo cp 90-touchpad.conf /etc/X11/xorg.conf.d/
sudo cp 10-intel.conf /etc/X11/xorg.conf.d/
cp .Xresources ~/
cp .xsettingsd ~/
mkdir -p ~/.config
mkdir -p ~/.fonts
cp -r .config/* ~/.config/
cp -r .fonts/* ~/.fonts/*
./install_termite
